# -*- coding: utf-8 -*-
"""Web_Scraper_UNOTaku_Anime_titles.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XmzqwErxt5LmVD2BSa7WrrAy0RwWFbHu
"""

# !pip install selenium
# !pip install datetime
# !pip install chromedriver_binary
# !pip install time
# !pip install datetime

import chromedriver_binary
import pandas as pd
import requests as req
import csv
from urllib.request import urlopen as uopen
from urllib.request import urlopen
from urllib.error import HTTPError
from urllib.error import URLError
from time import sleep
from urllib.request import urlopen
from bs4 import BeautifulSoup

PATH = "C:\Program Files (x86)\chromedriver.exe"
driver = webdriver.Chrome(PATH)
driver.get("https://myanimelist.net/topanime.php")
# From myanimelist, get all element links from the a elements with the class tag as follows:
# ' class="hoverinfo_trigger fl-l ml12 mr8" '. From each website, as though they were independently 
# clicked for the webpage hosting, extract the h1.titlename; 
# <h1 class="title-name h1_bold_none"><strong>Fullmetal Alchemist: Brotherhood</strong></h1>, and 
# extract its p payload where the p itemprop = 'description',